###
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: bob-csr
spec:
  groups:
    - system:authenticated
#  request: $(cat server.csr | base64 | tr -d '\n')
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1lUQ0NBVWtDQVFBd0hERU1NQW9HQTFVRUF3d0RZbTlpTVF3d0NnWURWUVFLREFObGJtY3dnZ0VpTUEwRwpDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3Bwc3JMaTZPdjJ2YThpSUE4dGY1UGtCQlVHT2Y2CmwzSmFVODRSdFRnem03cFQzYkZramVGNDJ1MnpQVitRRlJTc25MN3NFVTRxTzNvZERlY09PR0NXSXk1VzQ5amoKdlpsbUpKZUNmejhJZWxFMGJiS1daUlJZVXFveDBRMFViR2d0YXRtR3RDdG9JUFFzYnE1K0ZrVTFlQk0vRzFCZApPK1F2WG04aVFMazJKOElGWXJDajNXL0RPWTBhYldkUWllb1RVVHc0NUU3eFVnTVo0T1ZxSFdxVXB1SWF3dFU5CnowN1F3bDNtS2pENjl4ZmhEQWVjMlZyRVVEZDFpbnlhbGhqUlViNDNpcGxVSVNNV3VLaHFEZjI2d2VKdUx6Q0kKRi9DMlpzcVo4VjZpYkxvWVBZWjcyWm0vak1MV0dsR3U5Tm5mRll4dk9rRUJHNHVJLzROc3Y1RmZBZ01CQUFHZwpBREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBZVFKanVBKzM4eEpNd1p0UVhkejUwdk8wODlpOTdCbnpLUG1vCmJHUXNQZzQrdnJPSW5hUDF1UmllYlljczloeTFaNFR0U1BsL2YxbExOQkxQd1d2MTJIRkRhNHBFWFY0aHRLNTUKQ2FsNWJ5RVRMUjdIdk1FTTQwdE52NVFZS0hvdFZiOXFKR3ZCRUNhcFgvZGdxM1czZXU5RHJVbkVqc3ZaS1BJYgpGNSs2WmtIZngvR1c1MS9XcU8rQVA4eFd5UW52dVhjZ09wc29xanFYOTRpN3BSbmVWeThzVXRxZU9kaUs4NnhUCnQ4UVBLQXoyNHNmV09UNnBibGJjTXV0akdyUlRubHFPcmRQVzhRWDJLcjgrTnpHaEdPVXhPejdUNHdRZEZkelcKUUcxWlh5cFUzQXNHMUlFZHpUbzlJZUM4aFhCSVBmT0s4VXQ4TGd0NFlkYklJaEs2OHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  usages:
  - digital signature
  - key encipherment
  - server auth
